ALTER SESSION SET CONTAINER = CDB$ROOT;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE FORCE LOGGING;
ALTER SYSTEM ARCHIVE LOG CURRENT;

ALTER SYSTEM SET DB_RECOVERY_FILE_DEST_SIZE = 10G;
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST='/opt/oracle/oradata/recovery_area' SCOPE=SPFILE;



ALTER SESSION SET CONTAINER = CDB$ROOT;

CREATE TABLESPACE LOGMINER_TBS
       DATAFILE '/opt/oracle/oradata/XE/logminer_tbs.dbf'
       SIZE 50M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;


ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE LOGMINER_TBS
  	   DATAFILE '/opt/oracle/oradata/XE/XEPDB1/logminer_tbs01.dbf'
       SIZE 50M REUSE AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;



ALTER SESSION SET CONTAINER = CDB$ROOT;

CREATE USER c##dbzuser IDENTIFIED BY dbz
       DEFAULT TABLESPACE LOGMINER_TBS
       QUOTA UNLIMITED ON LOGMINER_TBS
       CONTAINER = ALL;

GRANT CREATE SESSION         TO c##dbzuser CONTAINER=ALL;
GRANT SET CONTAINER          TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE  TO c##dbzuser CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE    TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY TABLE       TO c##dbzuser CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE    TO c##dbzuser CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE   TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO c##dbzuser CONTAINER=ALL;
GRANT LOGMINING              TO c##dbzuser CONTAINER=ALL;


GRANT CREATE TABLE 			 TO c##dbzuser CONTAINER=ALL;
GRANT LOCK ANY TABLE 		 TO c##dbzuser CONTAINER=ALL;
GRANT CREATE SEQUENCE 		 TO c##dbzuser CONTAINER=ALL;


BEGIN
  DBMS_LOGMNR_D.BUILD(
        OPTIONS => DBMS_LOGMNR_D.STORE_IN_REDO_LOGS);
END;
/
