ALTER SESSION SET CONTAINER = CDB$ROOT;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE FORCE LOGGING;
ALTER SYSTEM ARCHIVE LOG CURRENT;

ALTER SYSTEM SET DB_RECOVERY_FILE_DEST_SIZE = 10G;
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST='/opt/oracle/oradata/recovery_area' SCOPE=SPFILE;

ALTER SYSTEM ARCHIVE LOG CURRENT;


CREATE TABLESPACE LOGMINER_TBS
       DATAFILE '/opt/oracle/oradata/XE/logminer_tbs.dbf'
       SIZE 50M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;


ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE LOGMINER_TBS
  	   DATAFILE '/opt/oracle/oradata/XE/XEPDB1/logminer_tbs01.dbf'
       SIZE 50M REUSE AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;



ALTER SESSION SET CONTAINER = CDB$ROOT;

CREATE USER c##dbzuser IDENTIFIED BY dbz
       DEFAULT TABLESPACE LOGMINER_TBS
       QUOTA UNLIMITED ON LOGMINER_TBS
       CONTAINER = ALL;

GRANT CREATE SESSION         TO c##dbzuser CONTAINER=ALL;
GRANT SET CONTAINER          TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE  TO c##dbzuser CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE    TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY TABLE       TO c##dbzuser CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE    TO c##dbzuser CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE   TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO c##dbzuser CONTAINER=ALL;
GRANT LOGMINING              TO c##dbzuser CONTAINER=ALL;


GRANT CREATE TABLE 			 TO c##dbzuser CONTAINER=ALL;
GRANT LOCK ANY TABLE 		 TO c##dbzuser CONTAINER=ALL;
GRANT CREATE SEQUENCE 		 TO c##dbzuser CONTAINER=ALL;


BEGIN
  DBMS_LOGMNR_D.BUILD(
        OPTIONS => DBMS_LOGMNR_D.STORE_IN_REDO_LOGS);
END;
/


ALTER SYSTEM ARCHIVE LOG CURRENT;




ALTER SESSION SET CONTAINER = XEPDB1;


CREATE USER AFADEEV IDENTIFIED BY AFADEEV123
    DEFAULT TABLESPACE LOGMINER_TBS
    QUOTA UNLIMITED ON LOGMINER_TBS;

GRANT CREATE SESSION TO AFADEEV;
GRANT CREATE TABLE TO AFADEEV;
GRANT CREATE SEQUENCE TO AFADEEV;
GRANT CREATE TRIGGER TO AFADEEV;
GRANT CREATE PROCEDURE TO AFADEEV;
GRANT CREATE VIEW TO AFADEEV;


CREATE TABLE AFADEEV.USERS (
	id      		INT generated as identity NOT NULL,
	first_name      VARCHAR2(64) NOT NULL,
	last_name     	VARCHAR2(64) NOT NULL,
	age 			INT NOT NULL,
	city     		VARCHAR2(64) NOT NULL,
	address     	VARCHAR2(256) NOT NULL,
	phone_number    VARCHAR2(64) NOT NULL,
	created_at    	TIMESTAMP(3) NOT NULL,
	updated_at    	TIMESTAMP(3) NOT NULL,
	constraint users_pk PRIMARY KEY(id)
 );

ALTER TABLE AFADEEV.USERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;



ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER SYSTEM ARCHIVE LOG CURRENT;

EXIT;
