ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER AFADEEV IDENTIFIED BY 123;
ALTER USER AFADEEV QUOTA unlimited ON SYSTEM;
GRANT CREATE SESSION, CONNECT, RESOURCE, DBA TO AFADEEV;
GRANT ALL PRIVILEGES TO AFADEEV;

CREATE TABLE AFADEEV.USERS (
	id      		INT generated as identity NOT NULL ,
	first_name     VARCHAR2(64) NOT NULL,
	last_name     	VARCHAR2(64) NOT NULL,
	age 			INT NOT NULL,
	city     		VARCHAR2(64) NOT NULL,
	address     	VARCHAR2(256) NOT NULL,
	phone_number    VARCHAR2(64) NOT NULL,
	created_at    	TIMESTAMP(3) NOT NULL,
	updated_at    	TIMESTAMP(3) NOT NULL,
	constraint users_pk PRIMARY KEY(id)
 );

ALTER TABLE AFADEEV.USERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

EXIT;