CREATE USER AFADEEV IDENTIFIED BY AFADEEV123
    DEFAULT TABLESPACE LOGMINER_TBS
    QUOTA UNLIMITED ON LOGMINER_TBS;

GRANT CREATE SESSION TO AFADEEV;
GRANT CREATE TABLE TO AFADEEV;
GRANT CREATE SEQUENCE TO AFADEEV;
GRANT CREATE TRIGGER TO AFADEEV;
GRANT CREATE PROCEDURE TO AFADEEV;
GRANT CREATE VIEW TO AFADEEV;


CREATE TABLE AFADEEV.USERS (
	id      		INT generated as identity NOT NULL,
	first_name      VARCHAR2(64) NOT NULL,
	last_name     	VARCHAR2(64) NOT NULL,
	age 			INT NOT NULL,
	city     		VARCHAR2(64) NOT NULL,
	address     	VARCHAR2(256) NOT NULL,
	phone_number    VARCHAR2(64) NOT NULL,
	created_at    	TIMESTAMP(3) NOT NULL,
	updated_at    	TIMESTAMP(3) NOT NULL,
	constraint users_pk PRIMARY KEY(id)
 );

ALTER TABLE AFADEEV.USERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

EXIT;